<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-NN2AJ9IO" failures="1" tests="4" name="testPack.UrbanLadderTestClass" time="66.261" errors="0" timestamp="2020-08-26T16:49:52 IST" skipped="0">
  <testcase classname="testPack.UrbanLadderTestClass" name="test1" time="18.426"/>
  <system-out/>
  <testcase classname="testPack.UrbanLadderTestClass" name="Test2" time="30.092"/>
  <system-out/>
  <testcase classname="testPack.UrbanLadderTestClass" name="Test3" time="17.652"/>
  <system-out/>
  <testcase classname="testPack.UrbanLadderTestClass" name="Test4" time="0.091">
    <failure message="expected [Open Bookshelves: Check 4 Amazing Designs &amp; Buy Online - Urban Ladder] but found [Open Bookshelves: Check 7 Amazing Designs &amp; Buy Online - Urban Ladder]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Open Bookshelves: Check 4 Amazing Designs & Buy Online - Urban Ladder] but found [Open Bookshelves: Check 7 Amazing Designs & Buy Online - Urban Ladder]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at basePack.PageBase.getTitle(PageBase.java:81)
at testPack.UrbanLadderTestClass.Test4(UrbanLadderTestClass.java:92)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Test4 -->
  <system-out/>
</testsuite> <!-- testPack.UrbanLadderTestClass -->
